2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Configure stats pid to 91308
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Loading settings from /home/shruti/.config/wandb/settings
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Loading settings from /home/shruti/workspaces/aerial_gym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/rl_games/wandb/settings
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'aerial_gym/rl_training/rl_games/runner.py', 'program_abspath': '/home/shruti/workspaces/aerial_gym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/rl_games/runner.py', 'program': 'runner.py'}
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_init.py:_log_setup():521] Logging user logs to /home/shruti/workspaces/aerial_gym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/rl_games/wandb/run-20250305_142051-swmznkku/logs/debug.log
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_init.py:_log_setup():522] Logging internal logs to /home/shruti/workspaces/aerial_gym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/rl_games/wandb/run-20250305_142051-swmznkku/logs/debug-internal.log
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_init.py:init():561] calling init triggers
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'params': {'seed': 8, 'algo': {'name': 'a2c_continuous'}, 'model': {'name': 'continuous_a2c_logstd'}, 'load_checkpoint': False, 'network': {'name': 'actor_critic', 'separate': False, 'space': {'continuous': {'mu_activation': 'None', 'sigma_activation': 'None', 'mu_init': {'name': 'default'}, 'sigma_init': {'name': 'const_initializer', 'val': 0}, 'fixed_sigma': True}}, 'mlp': {'units': [256, 128, 64], 'd2rl': False, 'activation': 'elu', 'initializer': {'name': 'default', 'scale': 2}}}, 'config': {'env_name': 'dce_navigation_task', 'env_config': {'num_envs': 512, 'headless': True, 'use_warp': True}, 'name': 'gen_ppo', 'reward_shaper': {'scale_value': 0.1}, 'normalize_advantage': True, 'gamma': 0.99, 'tau': 0.95, 'ppo': True, 'learning_rate': '1e-4', 'lr_schedule': 'adaptive', 'kl_threshold': 0.016, 'save_best_after': 10, 'score_to_win': 100000, 'grad_norm': 1.0, 'entropy_coef': 0.0001, 'truncate_grads': True, 'e_clip': 0.2, 'clip_value': False, 'num_actors': 512, 'horizon_length': 32, 'minibatch_size': 8192, 'mini_epochs': 4, 'critic_coef': 2, 'normalize_input': False, 'bounds_loss_coef': 0.0001, 'max_epochs': 400, 'normalize_value': True, 'use_diagnostics': True, 'value_bootstrap': True, 'use_smooth_clamp': False, 'player': {'use_vecenv': True}}}}
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_init.py:init():611] starting backend
2025-03-05 14:20:51,796 INFO    MainThread:91308 [wandb_init.py:init():615] setting up manager
2025-03-05 14:20:51,798 INFO    MainThread:91308 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-05 14:20:51,799 INFO    MainThread:91308 [wandb_init.py:init():623] backend started and connected
2025-03-05 14:20:51,805 INFO    MainThread:91308 [wandb_init.py:init():715] updated telemetry
2025-03-05 14:20:51,816 INFO    MainThread:91308 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-03-05 14:20:51,963 ERROR   MainThread:91308 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-03-05 14:20:52,049 ERROR   MainThread:91308 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/shruti/miniconda3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/shruti/miniconda3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-03-05 14:20:53,054 WARNING MsgRouterThr:91308 [router.py:message_loop():77] message_loop has been closed
